// ...existing code...
name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: steam-ds

    steps:
      - uses: actions/checkout@v3
        with:
          # ensure the repo is checked out so the steam-ds folder is available
          fetch-depth: 0

      # Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc

      # Pull DVC data (runs in steam-ds/)
      - name: Pull DVC data
        run: dvc pull

      # Run tests (runs in steam-ds/)
      - name: Run tests
        run: |
          pytest tests/

      # Linting (runs in steam-ds/)
      - name: Lint code
        run: |
          flake8 .
// ...existing code...
